import { theme as antdTheme } from 'antd';
import type { ThemeConfig } from 'antd';
import { appTheme } from '@/theme/appTheme';
import {
  THEME_PRESET_HEX,
  THEME_SECONDARY_HEX,
  type ThemePreset,
} from '@/store/preferencesStore';

/** Tailwind 语义色变量对应的 RGB 值（与 preferencesStore 同步） */
const TW_LIGHT_TOKENS = {
  surface: 'rgb(244 245 247)',
  surfaceContainerLowest: 'rgb(255 255 255)',
  surfaceContainerLow: 'rgb(242 244 246)',
  surfaceContainerHigh: 'rgb(230 232 234)',
  onSurface: 'rgb(23 43 77)',
  onSurfaceVariant: 'rgb(68 84 111)',
  outlineVariant: 'rgb(220 223 228)',
} as const;

const TW_DARK_TOKENS = {
  surface: 'rgb(15 23 42)',
  surfaceContainerLowest: 'rgb(30 41 59)',
  surfaceContainerLow: 'rgb(51 65 85)',
  surfaceContainerHigh: 'rgb(71 85 105)',
  onSurface: 'rgb(226 232 240)',
  onSurfaceVariant: 'rgb(148 163 184)',
  outlineVariant: 'rgb(51 65 85)',
} as const;

/** Ant Design 与个性化主色 / 明暗同步，避免卡片与门户 Tailwind 割裂 */
export function buildAntdTheme(preset: ThemePreset, dark: boolean): ThemeConfig {
  const colorPrimary = THEME_PRESET_HEX[preset];
  const colorInfo = THEME_SECONDARY_HEX[preset];
  const tw = dark ? TW_DARK_TOKENS : TW_LIGHT_TOKENS;

  const baseToken = {
    ...appTheme.token,
    colorPrimary,
    colorInfo,
    colorLink: colorPrimary,
  };

  if (dark) {
    return {
      algorithm: antdTheme.darkAlgorithm,
      token: {
        ...baseToken,
        colorBgLayout: tw.surface,
        colorBgContainer: tw.surfaceContainerLowest,
        colorBgElevated: tw.surfaceContainerLow,
        colorBorder: tw.outlineVariant,
        colorBorderSecondary: tw.surfaceContainerLow,
        colorText: tw.onSurface,
        colorTextSecondary: tw.onSurfaceVariant,
        colorTextTertiary: 'rgb(148 163 184)',
        colorTextQuaternary: 'rgb(100 116 139)',
        colorFill: 'rgb(51 65 85)',
        colorFillSecondary: 'rgb(71 85 105)',
        colorFillTertiary: 'rgb(100 116 139)',
        colorFillQuaternary: 'rgb(30 41 59)',
      },
      components: {
        Button: {
          defaultBg: tw.surfaceContainerLow,
          defaultColor: tw.onSurface,
          defaultBorderColor: tw.outlineVariant,
          defaultHoverBg: 'rgb(71 85 105)',
          defaultHoverColor: tw.onSurface,
          defaultHoverBorderColor: 'rgb(100 116 139)',
          defaultActiveBg: 'rgb(51 65 85)',
          defaultActiveColor: tw.onSurface,
          defaultActiveBorderColor: tw.outlineVariant,
          primaryColor: '#f8fafc',
          primaryHoverColor: '#f8fafc',
          primaryActiveColor: '#f8fafc',
          textTextColor: tw.onSurface,
          textTextHoverColor: colorPrimary,
          textTextActiveColor: colorPrimary,
          ghostTextColor: colorPrimary,
          ghostHoverTextColor: colorPrimary,
          ghostActiveTextColor: colorPrimary,
        },
        Input: {
          colorBgContainer: tw.surfaceContainerLowest,
          colorBorder: tw.outlineVariant,
          colorText: tw.onSurface,
          colorTextPlaceholder: 'rgb(100 116 139)',
          hoverBorderColor: colorPrimary,
          activeBorderColor: colorPrimary,
          activeShadow: `0 0 0 2px ${colorPrimary}20`,
          colorBgContainerDisabled: 'rgb(30 41 59)',
          colorTextDisabled: 'rgb(100 116 139)',
          colorBorderDisabled: 'rgb(51 65 85)',
          addonBg: tw.surfaceContainerLow,
          activeBg: tw.surfaceContainerLowest,
        },
        InputNumber: {
          colorBgContainer: tw.surfaceContainerLowest,
          colorBorder: tw.outlineVariant,
          colorText: tw.onSurface,
          colorTextPlaceholder: 'rgb(100 116 139)',
          hoverBorderColor: colorPrimary,
          activeBorderColor: colorPrimary,
          activeShadow: `0 0 0 2px ${colorPrimary}20`,
          colorBgContainerDisabled: 'rgb(30 41 59)',
          colorTextDisabled: 'rgb(100 116 139)',
          colorBorderDisabled: 'rgb(51 65 85)',
        },
        Select: {
          colorBgContainer: tw.surfaceContainerLowest,
          colorBgElevated: tw.surfaceContainerLow,
          colorBorder: tw.outlineVariant,
          colorText: tw.onSurface,
          colorTextPlaceholder: 'rgb(100 116 139)',
          optionSelectedBg: 'rgb(51 65 85)',
          optionActiveBg: 'rgb(71 85 105)',
          selectorBg: tw.surfaceContainerLowest,
          multipleItemBg: 'rgb(51 65 85)',
          multipleItemBorderColor: 'rgb(71 85 105)',
          multipleItemColor: tw.onSurface,
          hoverBorderColor: colorPrimary,
          activeBorderColor: colorPrimary,
          activeShadow: `0 0 0 2px ${colorPrimary}20`,
          colorBgContainerDisabled: 'rgb(30 41 59)',
          colorTextDisabled: 'rgb(100 116 139)',
          colorBorderDisabled: 'rgb(51 65 85)',
        },
        Table: {
          headerBg: tw.surfaceContainerLow,
          headerColor: tw.onSurface,
          headerSortActiveBg: 'rgb(71 85 105)',
          headerSortHoverBg: 'rgb(51 65 85)',
          rowHoverBg: 'rgb(51 65 85 / 0.5)',
          rowSelectedBg: 'rgb(51 65 85 / 0.7)',
          rowSelectedHoverBg: 'rgb(71 85 105 / 0.5)',
          bodySortBg: 'rgb(30 41 59)',
          borderColor: tw.outlineVariant,
          headerSplitColor: tw.outlineVariant,
          footerBg: tw.surfaceContainerLow,
          footerColor: tw.onSurfaceVariant,
          cellPaddingBlock: 16,
          cellPaddingInline: 16,
        },
        Card: {
          colorBgContainer: tw.surfaceContainerLowest,
          colorBorderSecondary: tw.outlineVariant,
          colorText: tw.onSurface,
          colorTextDescription: tw.onSurfaceVariant,
          headerBg: 'transparent',
          headerFontSize: 16,
          headerFontSizeSM: 14,
          paddingLG: 24,
        },
        Menu: {
          colorBgContainer: 'transparent',
          itemColor: tw.onSurfaceVariant,
          itemHoverColor: tw.onSurface,
          subMenuItemSelectedColor: colorPrimary,
          itemSelectedColor: colorPrimary,
          itemHoverBg: 'rgb(51 65 85 / 0.5)',
          itemActiveBg: 'rgb(51 65 85 / 0.7)',
          itemSelectedBg: 'rgb(51 65 85)',
          subMenuItemBg: tw.surfaceContainerLowest,
          itemDisabledColor: 'rgb(100 116 139)',
          horizontalItemSelectedColor: colorPrimary,
          horizontalItemHoverColor: colorPrimary,
          darkItemBg: 'transparent',
          darkItemColor: tw.onSurfaceVariant,
          darkItemHoverColor: tw.onSurface,
          darkItemActiveBg: 'rgb(51 65 85)',
          darkItemSelectedBg: 'rgb(51 65 85)',
          darkSubMenuItemBg: tw.surfaceContainerLowest,
        },
        Drawer: {
          colorBgElevated: tw.surfaceContainerLowest,
          colorBgMask: 'rgb(15 23 42 / 0.6)',
          colorText: tw.onSurface,
          colorTextDescription: tw.onSurfaceVariant,
          footerBg: tw.surfaceContainerLowest,
        },
        Modal: {
          headerBg: tw.surfaceContainerLowest,
          contentBg: tw.surfaceContainerLowest,
          footerBg: tw.surfaceContainerLowest,
          titleColor: tw.onSurface,
          colorText: tw.onSurface,
          colorTextSecondary: tw.onSurfaceVariant,
          contentBorderColor: tw.outlineVariant,
        },
        Radio: {
          buttonCheckedBg: colorPrimary,
          buttonColor: tw.onSurfaceVariant,
          buttonSolidCheckedColor: '#f8fafc',
          buttonSolidCheckedBg: colorPrimary,
          buttonBg: tw.surfaceContainerLow,
          buttonHoverBg: 'rgb(71 85 105)',
          colorText: tw.onSurface,
          radioBg: tw.surfaceContainerLowest,
          dotColor: colorPrimary,
          dotSize: 8,
        },
        Checkbox: {
          colorText: tw.onSurface,
          colorBgContainer: tw.surfaceContainerLowest,
          colorBorder: tw.outlineVariant,
          colorPrimary: colorPrimary,
          colorPrimaryHover: colorPrimary,
          colorPrimaryActive: colorPrimary,
        },
        Switch: {
          colorText: tw.onSurface,
          colorTextDisabled: 'rgb(100 116 139)',
          handleBg: tw.onSurface,
          handleShadow: '0 2px 4px rgb(0 0 0 / 0.2)',
          trackHeight: 22,
          trackMinWidth: 44,
        },
        Tag: {
          defaultBg: tw.surfaceContainerLow,
          defaultColor: tw.onSurface,
          colorText: tw.onSurface,
        },
        Tabs: {
          colorText: tw.onSurfaceVariant,
          colorTextActive: tw.onSurface,
          colorTextDisabled: 'rgb(100 116 139)',
          cardBg: tw.surfaceContainerLow,
          cardGutter: 4,
          cardPadding: '8px 16px',
          horizontalItemPadding: '12px 16px',
          horizontalItemHoverColor: colorPrimary,
          horizontalItemSelectedColor: colorPrimary,
          inkBarColor: colorPrimary,
        },
        Form: {
          labelColor: tw.onSurfaceVariant,
          labelFontSize: 14,
          labelColonMarginInlineEnd: 8,
          labelColonMarginInlineStart: 2,
          labelRequiredMarkColor: 'rgb(239 68 68)',
          verticalLabelPadding: '0 0 8px',
          verticalLabelMargin: 0,
        },
        DatePicker: {
          colorBgContainer: tw.surfaceContainerLowest,
          colorBgElevated: tw.surfaceContainerLow,
          colorBorder: tw.outlineVariant,
          colorText: tw.onSurface,
          colorTextPlaceholder: 'rgb(100 116 139)',
          colorTextDisabled: 'rgb(100 116 139)',
          colorBgContainerDisabled: 'rgb(30 41 59)',
          colorBorderDisabled: 'rgb(51 65 85)',
          hoverBorderColor: colorPrimary,
          activeBorderColor: colorPrimary,
          activeShadow: `0 0 0 2px ${colorPrimary}20`,
          cellActiveWithRangeBg: 'rgb(51 65 85)',
          cellHoverBg: 'rgb(71 85 105)',
          cellRangeBorderColor: colorPrimary,
          headerBg: tw.surfaceContainerLow,
          headerColor: tw.onSurface,
          yearControlWidth: 80,
          monthControlWidth: 70,
          cellWidth: 36,
          cellHeight: 32,
        },
        Tooltip: {
          colorBgSpotlight: 'rgb(51 65 85)',
          colorTextLightSolid: tw.onSurface,
          borderRadius: 6,
          fontSize: 12,
        },
        Popover: {
          colorBgElevated: tw.surfaceContainerLow,
          colorText: tw.onSurface,
          colorTextDescription: tw.onSurfaceVariant,
          colorBorder: tw.outlineVariant,
        },
        Dropdown: {
          colorBgElevated: tw.surfaceContainerLow,
          colorText: tw.onSurface,
          colorTextDisabled: 'rgb(100 116 139)',
          controlItemBgHover: 'rgb(71 85 105)',
          controlItemBgActive: 'rgb(51 65 85)',
          controlItemBgActiveHover: 'rgb(71 85 105)',
          paddingBlock: 4,
          paddingInline: 8,
        },
        Pagination: {
          colorText: tw.onSurfaceVariant,
          colorTextDisabled: 'rgb(100 116 139)',
          colorBgContainer: 'transparent',
          colorBgTextHover: 'rgb(51 65 85)',
          colorBgTextActive: 'rgb(71 85 105)',
          itemActiveBg: colorPrimary,
          itemActiveColorDisabled: 'rgb(100 116 139)',
          itemInputBg: tw.surfaceContainerLowest,
          itemLinkBg: tw.surfaceContainerLow,
          itemSize: 32,
          itemSizeSM: 28,
        },
        Breadcrumb: {
          colorText: tw.onSurfaceVariant,
          colorTextHover: colorPrimary,
          colorTextActive: colorPrimary,
          lastItemColor: tw.onSurface,
          iconFontSize: 14,
          linkColor: tw.onSurfaceVariant,
          linkHoverColor: colorPrimary,
          separatorColor: tw.onSurfaceVariant,
        },
        Divider: {
          colorSplit: tw.outlineVariant,
          colorText: tw.onSurface,
          textPaddingInline: 16,
        },
        Alert: {
          colorText: tw.onSurface,
          colorTextHeading: tw.onSurface,
          colorBgContainer: tw.surfaceContainerLow,
          colorBorder: tw.outlineVariant,
        },
        Message: {
          colorText: tw.onSurface,
          colorTextHeading: tw.onSurface,
          colorBg: tw.surfaceContainerLow,
          colorBorder: tw.outlineVariant,
          colorBgElevated: tw.surfaceContainerLow,
        },
        Notification: {
          colorText: tw.onSurface,
          colorTextHeading: tw.onSurface,
          colorBg: tw.surfaceContainerLow,
          colorBorder: tw.outlineVariant,
          colorBgElevated: tw.surfaceContainerLow,
        },
        Progress: {
          colorText: tw.onSurface,
          remainingColor: 'rgb(51 65 85)',
          circleTextColor: tw.onSurface,
          defaultColor: colorPrimary,
        },
        Spin: {
          colorText: tw.onSurfaceVariant,
          colorPrimary: colorPrimary,
        },
        Empty: {
          colorText: tw.onSurfaceVariant,
          colorTextDisabled: 'rgb(100 116 139)',
        },
        Collapse: {
          colorText: tw.onSurface,
          colorTextHeading: tw.onSurface,
          colorBgContainer: tw.surfaceContainerLowest,
          colorBorder: tw.outlineVariant,
          headerBg: tw.surfaceContainerLow,
          contentBg: tw.surfaceContainerLowest,
          contentPadding: '16px 24px',
        },
        Tree: {
          colorText: tw.onSurface,
          colorTextDisabled: 'rgb(100 116 139)',
          colorBgContainer: 'transparent',
          nodeHoverBg: 'rgb(51 65 85 / 0.5)',
          nodeSelectedBg: 'rgb(51 65 85)',
          directoryNodeSelectedBg: 'rgb(51 65 85)',
          directoryNodeSelectedColor: tw.onSurface,
          titleHeight: 28,
          nodePaddingBlock: 4,
        },
        List: {
          colorText: tw.onSurface,
          colorTextDescription: tw.onSurfaceVariant,
          colorBorder: tw.outlineVariant,
          colorSplit: tw.outlineVariant,
          colorBgContainer: 'transparent',
          colorBgTextHover: 'rgb(51 65 85 / 0.5)',
          headerBg: tw.surfaceContainerLow,
          footerBg: tw.surfaceContainerLow,
        },
        Steps: {
          colorText: tw.onSurface,
          colorTextDescription: tw.onSurfaceVariant,
          colorTextDisabled: 'rgb(100 116 139)',
          colorTextWaiting: tw.onSurfaceVariant,
          colorTextProcessing: colorPrimary,
          colorTextFinish: colorPrimary,
          colorTextError: 'rgb(239 68 68)',
          dotCurrentSize: 10,
          dotSize: 8,
          iconSize: 32,
          iconSizeSM: 24,
        },
        Timeline: {
          colorText: tw.onSurface,
          colorTextDescription: tw.onSurfaceVariant,
          dotBg: tw.surfaceContainerLowest,
          tailColor: tw.outlineVariant,
          itemPaddingBottom: 20,
        },
        Badge: {
          colorText: '#f8fafc',
          colorBgContainer: colorPrimary,
          colorBorder: 'transparent',
          dotSize: 6,
          indicatorHeight: 20,
          indicatorHeightSM: 16,
          textFontSize: 12,
          textFontSizeSM: 10,
        },
        Avatar: {
          colorText: '#f8fafc',
          colorBgContainer: 'rgb(71 85 105)',
          containerSize: 32,
          containerSizeLG: 40,
          containerSizeSM: 24,
          textFontSize: 14,
          textFontSizeLG: 18,
          textFontSizeSM: 12,
        },
        Segmented: {
          colorText: tw.onSurfaceVariant,
          colorTextHover: tw.onSurface,
          colorTextActive: tw.onSurface,
          colorBgContainer: tw.surfaceContainerLow,
          colorBgElevated: tw.surfaceContainerLowest,
          itemColor: tw.onSurfaceVariant,
          itemHoverColor: tw.onSurface,
          itemHoverBg: 'rgb(71 85 105)',
          itemSelectedColor: tw.onSurface,
          itemSelectedBg: tw.surfaceContainerLowest,
          itemActiveBg: 'rgb(71 85 105)',
          trackBg: tw.surfaceContainerLow,
          trackPadding: 4,
        },
        Slider: {
          colorText: tw.onSurface,
          colorTextQuaternary: 'rgb(100 116 139)',
          colorBgContainer: 'rgb(51 65 85)',
          colorBgElevated: tw.surfaceContainerLow,
          colorBorder: tw.outlineVariant,
          handleColor: colorPrimary,
          handleColorDisabled: 'rgb(100 116 139)',
          trackBg: colorPrimary,
          trackHoverBg: colorPrimary,
          railBg: 'rgb(51 65 85)',
          railHoverBg: 'rgb(71 85 105)',
          dotActiveBorderColor: colorPrimary,
          dotBorderColor: tw.outlineVariant,
          handleActiveColor: colorPrimary,
          handleSize: 14,
          handleSizeHover: 16,
          dotSize: 8,
          railSize: 4,
        },
        Transfer: {
          colorText: tw.onSurface,
          colorTextDisabled: 'rgb(100 116 139)',
          colorBgContainer: tw.surfaceContainerLowest,
          colorBgContainerDisabled: 'rgb(30 41 59)',
          colorBorder: tw.outlineVariant,
          colorBorderDisabled: 'rgb(51 65 85)',
          headerBg: tw.surfaceContainerLow,
          headerColor: tw.onSurface,
          headerDisabledColor: 'rgb(100 116 139)',
          bodyBg: tw.surfaceContainerLowest,
          itemHoverBg: 'rgb(51 65 85 / 0.5)',
          itemSelectedBg: 'rgb(51 65 85)',
          itemActiveBg: 'rgb(71 85 105)',
        },
      } as any,
    };
  }

  return {
    algorithm: antdTheme.defaultAlgorithm,
    token: {
      ...baseToken,
      colorBgLayout: TW_LIGHT_TOKENS.surface,
      colorBgContainer: TW_LIGHT_TOKENS.surfaceContainerLowest,
      colorBgElevated: TW_LIGHT_TOKENS.surfaceContainerLowest,
      colorBorder: TW_LIGHT_TOKENS.outlineVariant,
      colorBorderSecondary: 'rgb(230 232 236)',
      colorText: TW_LIGHT_TOKENS.onSurface,
      colorTextSecondary: TW_LIGHT_TOKENS.onSurfaceVariant,
      colorFill: 'rgb(242 244 246)',
      colorFillSecondary: 'rgb(230 232 234)',
      colorFillTertiary: 'rgb(220 223 228)',
      colorFillQuaternary: 'rgb(244 245 247)',
    },
    components: {
      Button: {
        defaultBg: TW_LIGHT_TOKENS.surfaceContainerLowest,
        defaultColor: TW_LIGHT_TOKENS.onSurface,
        defaultBorderColor: TW_LIGHT_TOKENS.outlineVariant,
        defaultHoverBg: TW_LIGHT_TOKENS.surfaceContainerLow,
        defaultHoverColor: TW_LIGHT_TOKENS.onSurface,
        defaultHoverBorderColor: 'rgb(200 203 208)',
        primaryColor: '#ffffff',
        textTextColor: TW_LIGHT_TOKENS.onSurface,
        textTextHoverColor: colorPrimary,
      },
      Input: {
        colorBgContainer: TW_LIGHT_TOKENS.surfaceContainerLowest,
        colorBorder: TW_LIGHT_TOKENS.outlineVariant,
        colorText: TW_LIGHT_TOKENS.onSurface,
        colorTextPlaceholder: 'rgb(114 119 128)',
        hoverBorderColor: colorPrimary,
        activeBorderColor: colorPrimary,
        activeShadow: `0 0 0 2px ${colorPrimary}20`,
        addonBg: TW_LIGHT_TOKENS.surfaceContainerLow,
      },
      Select: {
        colorBgContainer: TW_LIGHT_TOKENS.surfaceContainerLowest,
        colorBgElevated: TW_LIGHT_TOKENS.surfaceContainerLowest,
        colorBorder: TW_LIGHT_TOKENS.outlineVariant,
        colorText: TW_LIGHT_TOKENS.onSurface,
        colorTextPlaceholder: 'rgb(114 119 128)',
        optionSelectedBg: 'rgb(230 232 234)',
        optionActiveBg: 'rgb(242 244 246)',
        selectorBg: TW_LIGHT_TOKENS.surfaceContainerLowest,
        hoverBorderColor: colorPrimary,
        activeBorderColor: colorPrimary,
        activeShadow: `0 0 0 2px ${colorPrimary}20`,
      },
      Table: {
        headerBg: TW_LIGHT_TOKENS.surfaceContainerLow,
        headerColor: TW_LIGHT_TOKENS.onSurface,
        headerSortActiveBg: TW_LIGHT_TOKENS.surfaceContainerHigh,
        headerSortHoverBg: TW_LIGHT_TOKENS.surfaceContainerLow,
        rowHoverBg: 'rgb(242 244 246)',
        rowSelectedBg: 'rgb(230 232 234)',
        rowSelectedHoverBg: 'rgb(220 223 228)',
        bodySortBg: TW_LIGHT_TOKENS.surfaceContainerLow,
        borderColor: TW_LIGHT_TOKENS.outlineVariant,
        headerSplitColor: TW_LIGHT_TOKENS.outlineVariant,
        footerBg: TW_LIGHT_TOKENS.surfaceContainerLow,
        footerColor: TW_LIGHT_TOKENS.onSurfaceVariant,
        cellPaddingBlock: 16,
        cellPaddingInline: 16,
      },
      Card: {
        colorBgContainer: TW_LIGHT_TOKENS.surfaceContainerLowest,
        colorBorderSecondary: TW_LIGHT_TOKENS.outlineVariant,
        colorText: TW_LIGHT_TOKENS.onSurface,
        colorTextDescription: TW_LIGHT_TOKENS.onSurfaceVariant,
        headerBg: 'transparent',
      },
      Menu: {
        colorBgContainer: 'transparent',
        itemColor: TW_LIGHT_TOKENS.onSurfaceVariant,
        itemHoverColor: TW_LIGHT_TOKENS.onSurface,
        subMenuItemSelectedColor: colorPrimary,
        itemSelectedColor: colorPrimary,
        itemHoverBg: TW_LIGHT_TOKENS.surfaceContainerLow,
        itemActiveBg: TW_LIGHT_TOKENS.surfaceContainerLow,
        itemSelectedBg: TW_LIGHT_TOKENS.surfaceContainerLow,
        horizontalItemSelectedColor: colorPrimary,
        horizontalItemHoverColor: colorPrimary,
      },
      Modal: {
        headerBg: TW_LIGHT_TOKENS.surfaceContainerLowest,
        contentBg: TW_LIGHT_TOKENS.surfaceContainerLowest,
        footerBg: TW_LIGHT_TOKENS.surfaceContainerLowest,
        titleColor: TW_LIGHT_TOKENS.onSurface,
        colorText: TW_LIGHT_TOKENS.onSurface,
        colorTextSecondary: TW_LIGHT_TOKENS.onSurfaceVariant,
      },
      Radio: {
        buttonCheckedBg: colorPrimary,
        buttonColor: TW_LIGHT_TOKENS.onSurfaceVariant,
        buttonSolidCheckedColor: '#ffffff',
        buttonSolidCheckedBg: colorPrimary,
        colorText: TW_LIGHT_TOKENS.onSurface,
      },
      Form: {
        labelColor: TW_LIGHT_TOKENS.onSurfaceVariant,
        labelFontSize: 14,
      },
      DatePicker: {
        colorBgContainer: TW_LIGHT_TOKENS.surfaceContainerLowest,
        colorBgElevated: TW_LIGHT_TOKENS.surfaceContainerLowest,
        colorBorder: TW_LIGHT_TOKENS.outlineVariant,
        colorText: TW_LIGHT_TOKENS.onSurface,
        colorTextPlaceholder: 'rgb(114 119 128)',
        hoverBorderColor: colorPrimary,
        activeBorderColor: colorPrimary,
        activeShadow: `0 0 0 2px ${colorPrimary}20`,
        cellActiveWithRangeBg: TW_LIGHT_TOKENS.surfaceContainerLow,
        cellHoverBg: TW_LIGHT_TOKENS.surfaceContainerHigh,
        headerBg: TW_LIGHT_TOKENS.surfaceContainerLow,
        headerColor: TW_LIGHT_TOKENS.onSurface,
      },
      Dropdown: {
        colorBgElevated: TW_LIGHT_TOKENS.surfaceContainerLowest,
        colorText: TW_LIGHT_TOKENS.onSurface,
        controlItemBgHover: TW_LIGHT_TOKENS.surfaceContainerLow,
        controlItemBgActive: TW_LIGHT_TOKENS.surfaceContainerHigh,
      },
      Tooltip: {
        colorBgSpotlight: 'rgb(51 65 85)',
        colorTextLightSolid: '#ffffff',
      },
      Popover: {
        colorBgElevated: TW_LIGHT_TOKENS.surfaceContainerLowest,
        colorText: TW_LIGHT_TOKENS.onSurface,
        colorTextDescription: TW_LIGHT_TOKENS.onSurfaceVariant,
        colorBorder: TW_LIGHT_TOKENS.outlineVariant,
      },
      Pagination: {
        colorText: TW_LIGHT_TOKENS.onSurfaceVariant,
        colorBgContainer: 'transparent',
        colorBgTextHover: TW_LIGHT_TOKENS.surfaceContainerLow,
        colorBgTextActive: TW_LIGHT_TOKENS.surfaceContainerHigh,
        itemActiveBg: colorPrimary,
        itemInputBg: TW_LIGHT_TOKENS.surfaceContainerLowest,
      },
      Breadcrumb: {
        colorText: TW_LIGHT_TOKENS.onSurfaceVariant,
        colorTextHover: colorPrimary,
        colorTextActive: colorPrimary,
        lastItemColor: TW_LIGHT_TOKENS.onSurface,
      },
      Divider: {
        colorSplit: TW_LIGHT_TOKENS.outlineVariant,
        colorText: TW_LIGHT_TOKENS.onSurface,
      },
      Tag: {
        defaultBg: TW_LIGHT_TOKENS.surfaceContainerLow,
        defaultColor: TW_LIGHT_TOKENS.onSurface,
        colorText: TW_LIGHT_TOKENS.onSurface,
      },
      Tabs: {
        colorText: TW_LIGHT_TOKENS.onSurfaceVariant,
        colorTextActive: TW_LIGHT_TOKENS.onSurface,
        cardBg: TW_LIGHT_TOKENS.surfaceContainerLow,
        horizontalItemHoverColor: colorPrimary,
        horizontalItemSelectedColor: colorPrimary,
        inkBarColor: colorPrimary,
      },
      Alert: {
        colorText: TW_LIGHT_TOKENS.onSurface,
        colorTextHeading: TW_LIGHT_TOKENS.onSurface,
        colorBgContainer: TW_LIGHT_TOKENS.surfaceContainerLow,
        colorBorder: TW_LIGHT_TOKENS.outlineVariant,
      },
      Message: {
        colorText: TW_LIGHT_TOKENS.onSurface,
        colorTextHeading: TW_LIGHT_TOKENS.onSurface,
        colorBg: TW_LIGHT_TOKENS.surfaceContainerLowest,
        colorBorder: TW_LIGHT_TOKENS.outlineVariant,
        colorBgElevated: TW_LIGHT_TOKENS.surfaceContainerLowest,
      },
      Notification: {
        colorText: TW_LIGHT_TOKENS.onSurface,
        colorTextHeading: TW_LIGHT_TOKENS.onSurface,
        colorBg: TW_LIGHT_TOKENS.surfaceContainerLowest,
        colorBorder: TW_LIGHT_TOKENS.outlineVariant,
        colorBgElevated: TW_LIGHT_TOKENS.surfaceContainerLowest,
      },
      Steps: {
        colorText: TW_LIGHT_TOKENS.onSurface,
        colorTextDescription: TW_LIGHT_TOKENS.onSurfaceVariant,
        colorTextProcessing: colorPrimary,
        colorTextFinish: colorPrimary,
      },
      Badge: {
        colorText: '#ffffff',
        colorBgContainer: colorPrimary,
      },
      Avatar: {
        colorText: '#ffffff',
        colorBgContainer: TW_LIGHT_TOKENS.surfaceContainerHigh,
      },
      Segmented: {
        colorText: TW_LIGHT_TOKENS.onSurfaceVariant,
        colorTextHover: TW_LIGHT_TOKENS.onSurface,
        colorTextActive: TW_LIGHT_TOKENS.onSurface,
        colorBgContainer: TW_LIGHT_TOKENS.surfaceContainerLow,
        colorBgElevated: TW_LIGHT_TOKENS.surfaceContainerLowest,
        itemSelectedColor: TW_LIGHT_TOKENS.onSurface,
        itemSelectedBg: TW_LIGHT_TOKENS.surfaceContainerLowest,
        trackBg: TW_LIGHT_TOKENS.surfaceContainerLow,
      },
      Slider: {
        handleColor: colorPrimary,
        handleColorDisabled: 'rgb(200 203 208)',
        trackBg: colorPrimary,
        trackHoverBg: colorPrimary,
        railBg: TW_LIGHT_TOKENS.surfaceContainerHigh,
        railHoverBg: TW_LIGHT_TOKENS.outlineVariant,
        dotActiveBorderColor: colorPrimary,
        dotBorderColor: TW_LIGHT_TOKENS.outlineVariant,
      },
      Transfer: {
        colorText: TW_LIGHT_TOKENS.onSurface,
        colorBgContainer: TW_LIGHT_TOKENS.surfaceContainerLowest,
        colorBorder: TW_LIGHT_TOKENS.outlineVariant,
        headerBg: TW_LIGHT_TOKENS.surfaceContainerLow,
        headerColor: TW_LIGHT_TOKENS.onSurface,
        bodyBg: TW_LIGHT_TOKENS.surfaceContainerLowest,
        itemHoverBg: TW_LIGHT_TOKENS.surfaceContainerLow,
        itemSelectedBg: TW_LIGHT_TOKENS.surfaceContainerHigh,
      },
    } as any,
  };
}
